# model
model_name_or_path: '/home/calvinzhang/Documents/llm/bloom-7b1'
# data
dataset_name: 'math250k'
refresh: false
data_tag: 'base'
train_on_inputs: false
data_max_length: 512  # original 1024
# training
# trainer
tag: 'lomo'
output_dir: 'outputs'
overwrite_output_dir: true
deepspeed: 'config/ds_config.json'
do_train: true
do_eval: False
evaluation_strategy: 'epoch'
per_device_train_batch_size: 2  # original 16
per_device_eval_batch_size: 2  # original 16
learning_rate: 0.005  # original 0.03 when batch size is 16
weight_decay: 0
num_train_epochs: 5  # oroginal 10
lr_scheduler_type: 'linear'
warmup: 0.1
clip_grad_norm: 1.0
# please set `resume_from_checkpoint` to load checkpoints.
#resume_from_checkpoint: 'outputs/wic_7B_lomo/output_adamw_hf_lr0.03_bs16_warmup0.1_clipnorm1.0/checkpoint-0'
# please set `save_strategy` (`no`, `epoch`, `steps`) and `save_total_limit` (the max amount of checkpoints) to save checkpoints.
save_strategy: 'no'
save_total_limit: 0
seed: 42
#bf16: true
remove_unused_columns: false
load_best_model_at_end: false
metric_for_best_model: 'acc'
group_by_length: false
#report_to: 'wandb'
dataloader_pin_memory: false
gradient_checkpointing: true
predict_with_generate: false
